# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Paired drive-response probe: isolate the articulation/drive integration.

Why this exists
---------------
Three rounds of read-back diffing have found *no* difference between the Isaac
Sim driver (``test_tracker_isaacsim.py``) and IsaacLab training
(``trace_tracker_isaaclab.py``): identical per-joint solver properties,
identical per-link rigid-body properties, identical scene config, identical
timing, identical state and identical action.  Yet per-control-step resync
(``--resync-state``) measures the driver's joints coming out of one 20 ms
control step **44% faster** than IsaacLab's, correlated 0.91 with joint speed
and concentrated in the knees.

Every probe so far has been *behavioural under load*: the robot is standing on
the ground, so drive torque, gravity, contact and multibody coupling are summed
into one number.  This probe removes everything except the drive:

* the robot is teleported **5 m into the air**, so there is no contact at all;
* both stacks are written the **same** root pose/velocity and joint pos/vel;
* both stacks are given the **same** constant PD target;
* both step exactly ``decimation`` physics substeps with no controller in the
  loop, recording joint state **after every substep**.

Gravity still acts, but it acts on verified-identical masses, inertias and COMs
from a verified-identical state, so it contributes identically to both stacks --
and the ``gravity_only`` case (target = current position, zero velocity) makes
that assumption falsifiable rather than assumed: if *that* case diverges, the
difference is in the articulation integrator itself and has nothing to do with
the drive.

The case set is designed so a divergence names its own cause:

``gravity_only``
    Zero position error, zero velocity.  Drive torque is ~0, so any divergence
    is articulation integration / gravity, not the drive law.
``step_*``
    Zero velocity, pure position error.  Isolates the **stiffness** term.  A
    divergence scaling with the offset amplitude is a stiffness-side difference
    (units, drive type, effort clamp).
``damp_*``
    Zero position error, non-zero velocity.  Isolates the **damping** term --
    the one the resync probe points at.  A divergence scaling with the velocity
    amplitude is a damping-side difference.
``mixed_*``
    Both terms at once, at speeds comparable to the real clip.
``tape_*``
    Real recorded joint configurations and joint speeds from the IsaacLab run,
    lifted out of contact.  Realistic, but still contact-free.

Because the two stacks share one spec file and one result schema, the
comparison is a pure array diff with no re-derivation on either side.

Usage
-----
The spec is generated by the IsaacLab harness (it owns the robot config and the
post-reset state that anchors the cases)::

    # 1. IsaacLab: write the spec and run it
    python deployment/trace_tracker_isaaclab.py \\
        --checkpoint results/g1_walk_box/score_based.ckpt \\
        --motion-file results/g1_walk_box/g1_walk_box.pt \\
        --out-dir /tmp/isaaclab_trace --headless \\
        --drive-probe-out /tmp/isaaclab_trace/drive_probe_isaaclab.npz \\
        --drive-probe-tape /tmp/isaaclab_trace/context_isaaclab.npz

    # 2. Isaac Sim driver: run the same spec
    python deployment/test_tracker_isaacsim.py \\
        --onnx results/g1_walk_box/compiled_models/unified_pipeline.onnx \\
        --motion results/g1_walk_box/g1_walk_box.pt --robot g1 \\
        --device cuda:0 --joint-friction off --headless \\
        --drive-probe /tmp/isaaclab_trace/drive_probe_spec.npz \\
        --drive-probe-out /tmp/drive_probe_driver.npz

    # 3. Compare (no simulator needed)
    python -m deployment.drive_probe --compare \\
        /tmp/isaaclab_trace/drive_probe_isaaclab.npz /tmp/drive_probe_driver.npz
"""

from __future__ import annotations

import argparse
import math

import numpy as np

# Spec arrays are copied into every result file so a result is self-describing
# and a comparison can assert both stacks ran the *same* cases.
SPEC_KEYS = (
    "spec__labels",
    "spec__root_pos",
    "spec__root_quat_xyzw",
    "spec__root_lin_vel",
    "spec__root_ang_vel",
    "spec__dof_pos",
    "spec__dof_vel",
    "spec__target",
    "spec__joint_names",
    "spec__substeps",
    "spec__physics_dt",
)


def _pattern(n: int, phase: float) -> np.ndarray:
    """A deterministic, zero-mean, order-dependent per-joint pattern in [-1, 1].

    Deliberately not ``np.random``: the spec is written by one process and read
    by another on a different simulator stack, and a seeded RNG would still tie
    the numbers to a NumPy version.  ``sin`` of the joint index is reproducible
    forever and spreads sign and magnitude across the kinematic tree.
    """
    return np.sin(np.arange(n, dtype=np.float64) * 1.7 + phase)


def build_spec(
    joint_names,
    base_root_pos,
    base_root_quat_xyzw,
    default_dof_pos,
    substeps: int,
    physics_dt: float,
    lift: float = 5.0,
    tape: dict | None = None,
    tape_steps=(60, 120, 180, 240),
) -> dict:
    """Assemble the probe cases.

    Args:
        joint_names: Policy-order joint names ``[N]``.
        base_root_pos: World root position to anchor the cases on ``[3]``; the
            post-reset root position, so the robot lands somewhere the ground
            actually exists (irrelevant while airborne, but it keeps the case
            inside any terrain mesh if ``lift`` is ever set to 0).
        base_root_quat_xyzw: World root orientation to anchor on ``[4]``.
        default_dof_pos: Joint positions the synthetic cases perturb ``[N]``,
            policy order.
        substeps: Physics substeps per control step (``decimation``).
        physics_dt: Physics timestep, recorded so the comparison can check that
            both stacks integrated the same amount of time.
        lift: Metres to raise the root by, to guarantee no contact.
        tape: Optional ``context_isaaclab.npz`` contents, for the ``tape_*``
            cases.  Needs ``sim__dof_pos``, ``sim__dof_vel``, ``sim__root_pos``,
            ``sim__root_rot``, ``sim__root_lin_vel``, ``sim__root_ang_vel`` and
            ``processed_action``.
        tape_steps: Control-step indices to take ``tape_*`` cases from.

    Returns:
        A dict of ``spec__*`` arrays, ready for :func:`write_spec`.
    """
    n = len(joint_names)
    q0 = np.asarray(default_dof_pos, dtype=np.float64).reshape(n)
    root_pos = np.asarray(base_root_pos, dtype=np.float64).reshape(3) + np.array(
        [0.0, 0.0, lift]
    )
    root_quat = np.asarray(base_root_quat_xyzw, dtype=np.float64).reshape(4)
    pat_a = _pattern(n, 0.0)
    pat_b = _pattern(n, 1.1)

    labels, dof_pos, dof_vel, target = [], [], [], []
    root_pos_l, root_quat_l, lin_vel_l, ang_vel_l = [], [], [], []

    def add(label, q, qd, tgt, rp=None, rq=None, lv=None, av=None):
        labels.append(label)
        dof_pos.append(np.asarray(q, dtype=np.float64).reshape(n))
        dof_vel.append(np.asarray(qd, dtype=np.float64).reshape(n))
        target.append(np.asarray(tgt, dtype=np.float64).reshape(n))
        root_pos_l.append(root_pos if rp is None else np.asarray(rp, dtype=np.float64))
        root_quat_l.append(
            root_quat if rq is None else np.asarray(rq, dtype=np.float64)
        )
        lin_vel_l.append(
            np.zeros(3) if lv is None else np.asarray(lv, dtype=np.float64)
        )
        ang_vel_l.append(
            np.zeros(3) if av is None else np.asarray(av, dtype=np.float64)
        )

    zero = np.zeros(n)

    # Drive torque ~0: whatever this case shows is articulation integration.
    add("gravity_only", q0, zero, q0)

    # Stiffness only: zero velocity, pure position error.
    for amp in (0.05, 0.20):
        add(f"step_{amp:.2f}", q0, zero, q0 + amp * pat_a)

    # Damping only: zero position error, pure velocity.
    for vel in (1.0, 5.0, 10.0):
        add(f"damp_{vel:.1f}", q0, vel * pat_a, q0)

    # Both terms, at the speeds the real clip reaches (peak ~10 rad/s).
    add("mixed_slow", q0 + 0.05 * pat_b, 1.0 * pat_a, q0)
    add("mixed_fast", q0 + 0.20 * pat_b, 10.0 * pat_a, q0)

    # Real states, lifted out of contact.
    if tape is not None:
        n_steps = int(np.asarray(tape["sim__dof_pos"]).shape[0])
        for step in tape_steps:
            if step >= n_steps:
                continue
            add(
                f"tape_{step:03d}",
                np.asarray(tape["sim__dof_pos"])[step],
                np.asarray(tape["sim__dof_vel"])[step],
                np.asarray(tape["processed_action"])[step],
                rp=np.asarray(tape["sim__root_pos"])[step] + np.array([0.0, 0.0, lift]),
                rq=np.asarray(tape["sim__root_rot"])[step],
                lv=np.asarray(tape["sim__root_lin_vel"])[step],
                av=np.asarray(tape["sim__root_ang_vel"])[step],
            )

    return {
        "spec__labels": np.array(labels),
        "spec__root_pos": np.stack(root_pos_l),
        "spec__root_quat_xyzw": np.stack(root_quat_l),
        "spec__root_lin_vel": np.stack(lin_vel_l),
        "spec__root_ang_vel": np.stack(ang_vel_l),
        "spec__dof_pos": np.stack(dof_pos),
        "spec__dof_vel": np.stack(dof_vel),
        "spec__target": np.stack(target),
        "spec__joint_names": np.array(list(joint_names)),
        "spec__substeps": np.asarray(int(substeps)),
        "spec__physics_dt": np.asarray(float(physics_dt)),
    }


def write_spec(path, spec: dict) -> None:
    np.savez(str(path), **spec)


def load_spec(path) -> dict:
    data = np.load(str(path), allow_pickle=True)
    missing = [k for k in SPEC_KEYS if k not in data.files]
    if missing:
        raise ValueError(f"{path} is not a drive-probe spec; missing {missing}")
    return {k: data[k] for k in SPEC_KEYS}


class ProbeRecorder:
    """Collects one stack's per-substep response to every spec case.

    Both harnesses drive this the same way::

        rec = ProbeRecorder(spec, stack="isaaclab")
        for case in range(rec.num_cases):
            <write the case's state>
            rec.sample(case)                 # index 0: the written state
            <apply the case's target>
            for _ in range(rec.substeps):
                <one physics substep>
                rec.sample(case)             # indices 1..substeps
        rec.write(path, target_readback=..., stiffness=..., ...)

    ``sample`` takes plain NumPy so neither harness has to agree with the other
    about tensor types or devices.
    """

    def __init__(self, spec: dict, stack: str) -> None:
        self.spec = spec
        self.stack = stack
        self.num_cases = int(spec["spec__labels"].shape[0])
        self.substeps = int(spec["spec__substeps"])
        self.num_dofs = int(spec["spec__dof_pos"].shape[1])
        shape = (self.num_cases, self.substeps + 1)
        self.dof_pos = np.full(shape + (self.num_dofs,), np.nan)
        self.dof_vel = np.full(shape + (self.num_dofs,), np.nan)
        self.root_pos = np.full(shape + (3,), np.nan)
        self.root_quat = np.full(shape + (4,), np.nan)
        self._cursor = [0] * self.num_cases

    def sample(self, case: int, dof_pos, dof_vel, root_pos, root_quat_xyzw) -> None:
        """Record one snapshot for ``case``; call order defines the substep index."""
        idx = self._cursor[case]
        if idx > self.substeps:
            raise IndexError(
                f"case {case} sampled {idx + 1} times for {self.substeps} substeps"
            )
        self.dof_pos[case, idx] = np.asarray(dof_pos, dtype=np.float64).reshape(-1)
        self.dof_vel[case, idx] = np.asarray(dof_vel, dtype=np.float64).reshape(-1)
        self.root_pos[case, idx] = np.asarray(root_pos, dtype=np.float64).reshape(3)
        self.root_quat[case, idx] = np.asarray(
            root_quat_xyzw, dtype=np.float64
        ).reshape(4)
        self._cursor[case] = idx + 1

    def write(self, path, **extras) -> None:
        """Write the result npz, embedding the spec so it is self-describing.

        Args:
            path: Output ``.npz`` path.
            extras: Optional arrays recorded alongside, all in policy order --
                ``target_readback`` ``[num_cases, N]`` (what PhysX reports as the
                position target *after* the write, the only check that the
                commanded action reached the solver) and the ``[N]`` properties
                ``stiffness``, ``damping``, ``armature``.  Anything that is
                ``None``, or a sequence with a ``None`` in it, is dropped rather
                than written as an object array: a read-back that failed must be
                *absent* from the result, not present and unusable.
        """
        payload = dict(self.spec)
        payload.update(
            {
                "res__stack": np.array(str(self.stack)),
                "res__dof_pos": self.dof_pos,
                "res__dof_vel": self.dof_vel,
                "res__root_pos": self.root_pos,
                "res__root_quat_xyzw": self.root_quat,
            }
        )
        for name, value in extras.items():
            if value is None:
                continue
            if isinstance(value, (list, tuple)) and any(v is None for v in value):
                continue
            payload[f"res__{name}"] = np.asarray(value, dtype=np.float64)
        np.savez(str(path), **payload)


def _quat_angle_deg(qa: np.ndarray, qb: np.ndarray) -> np.ndarray:
    """Geodesic angle between two xyzw quaternion arrays, in degrees."""
    dot = np.abs(np.sum(qa * qb, axis=-1))
    return np.degrees(2.0 * np.arccos(np.clip(dot, -1.0, 1.0)))


def compare(path_a, path_b) -> str:
    """Diff two probe results and format the report.

    Args:
        path_a: Reference result (conventionally the IsaacLab one).
        path_b: Result under test (conventionally the driver's).

    Returns:
        A printable report.
    """
    a = np.load(str(path_a), allow_pickle=True)
    b = np.load(str(path_b), allow_pickle=True)

    labels = [str(x) for x in a["spec__labels"]]
    if [str(x) for x in b["spec__labels"]] != labels:
        raise ValueError("the two results did not run the same cases")
    joints = [str(x) for x in a["spec__joint_names"]]
    substeps = int(a["spec__substeps"])
    if int(b["spec__substeps"]) != substeps:
        raise ValueError(
            f"substep count differs: {substeps} vs {int(b['spec__substeps'])}"
        )

    name_a = str(a["res__stack"]) if "res__stack" in a.files else str(path_a)
    name_b = str(b["res__stack"]) if "res__stack" in b.files else str(path_b)

    lines = [
        f"=== Drive-response probe: {name_a} vs {name_b} ===",
        f"  {len(labels)} cases, {substeps} substeps, "
        f"physics_dt={float(a['spec__physics_dt']):.6f}s, {len(joints)} joints",
        "",
    ]

    # --- did the commanded target reach PhysX on both stacks? --------------
    for tag, data in ((name_a, a), (name_b, b)):
        if "res__target_readback" not in data.files:
            lines.append(f"  {tag:10s} target read-back: <not recorded>")
            continue
        err = np.abs(data["res__target_readback"] - data["spec__target"])
        lines.append(
            f"  {tag:10s} target read-back max|commanded - PhysX| = {err.max():.3e} rad"
        )
    # The *velocity* target is the one read that can cancel the damping term
    # while leaving the stiffness term intact: PhysX applies
    # ``kp*(qTarget - q) + kd*(vTarget - v)``, so a vTarget that tracks v damps
    # nothing.  Neither stack ever commands one, so both must read back zero.
    for tag, data in ((name_a, a), (name_b, b)):
        if "res__vel_target_readback" not in data.files:
            lines.append(f"  {tag:16s} velocity target: <not recorded>")
            continue
        vt = data["res__vel_target_readback"]
        lines.append(
            f"  {tag:16s} velocity target read-back: max|vTarget| = "
            f"{np.abs(vt).max():.3e} rad/s"
        )
    for name in (
        "stiffness",
        "damping",
        "armature",
        "friction",
        "max_force",
        "max_velocity",
    ):
        key = f"res__{name}"
        if key in a.files and key in b.files:
            delta = np.abs(a[key] - b[key])
            verdict = "" if delta.max() < 1e-4 else "   ** DIFFERS **"
            lines.append(f"  {name:14s} max|d| = {delta.max():.6e}{verdict}")
        elif key in a.files or key in b.files:
            lines.append(f"  {name:14s} recorded on only one stack")
    lines.append("")

    # --- the state written must match, or nothing below means anything -----
    write_err = max(
        float(np.abs(a["res__dof_pos"][:, 0] - b["res__dof_pos"][:, 0]).max()),
        float(np.abs(a["res__dof_vel"][:, 0] - b["res__dof_vel"][:, 0]).max()),
    )
    lines.append(
        f"  initial-state agreement (substep 0): max|d| = {write_err:.3e} "
        + ("OK" if write_err < 1e-5 else "** THE TWO STACKS DID NOT START EQUAL **")
    )
    lines.append("")

    header = (
        f"  {'case':14s} {'|d q|inf':>10s} {'|d qd|inf':>10s} "
        f"{'qd rms A':>9s} {'qd rms B':>9s} {'ratio':>7s} "
        f"{'|d root|':>9s} {'worst joint':>24s}"
    )
    lines.append(f"  Per case, after the full control step (substep {substeps}):")
    lines.append(header)
    lines.append("  " + "-" * (len(header) - 2))

    for i, label in enumerate(labels):
        qa, qb = a["res__dof_pos"][i, substeps], b["res__dof_pos"][i, substeps]
        va, vb = a["res__dof_vel"][i, substeps], b["res__dof_vel"][i, substeps]
        dq, dv = np.abs(qa - qb), np.abs(va - vb)
        rms_a = float(np.sqrt(np.mean(va**2)))
        rms_b = float(np.sqrt(np.mean(vb**2)))
        ratio = rms_b / rms_a if rms_a > 1e-9 else math.nan
        droot = float(
            np.linalg.norm(
                a["res__root_pos"][i, substeps] - b["res__root_pos"][i, substeps]
            )
        )
        worst = joints[int(dv.argmax())]
        lines.append(
            f"  {label:14s} {dq.max():10.3e} {dv.max():10.3e} "
            f"{rms_a:9.4f} {rms_b:9.4f} {ratio:7.4f} "
            f"{droot:9.3e} {worst:>24s}"
        )

    # --- where in the control step does the divergence appear? -------------
    lines.append("")
    lines.append("  Divergence growth across substeps (max|d qd|inf over cases):")
    row = ["  substep      "]
    for s in range(substeps + 1):
        row.append(f"{s:>10d}")
    lines.append("".join(row))
    row = ["  |d qd|inf    "]
    for s in range(substeps + 1):
        dv = np.abs(a["res__dof_vel"][:, s] - b["res__dof_vel"][:, s]).max()
        row.append(f"{dv:10.3e}")
    lines.append("".join(row))
    row = ["  |d q|inf     "]
    for s in range(substeps + 1):
        dq = np.abs(a["res__dof_pos"][:, s] - b["res__dof_pos"][:, s]).max()
        row.append(f"{dq:10.3e}")
    lines.append("".join(row))
    row = ["  |d root quat|"]
    for s in range(substeps + 1):
        ang = _quat_angle_deg(
            a["res__root_quat_xyzw"][:, s], b["res__root_quat_xyzw"][:, s]
        ).max()
        row.append(f"{ang:10.3e}")
    lines.append("".join(row))
    lines.append("  (root quat in degrees; everything else rad / rad/s)")

    # --- verdict -----------------------------------------------------------
    lines.append("")
    by_case = {
        label: float(
            np.abs(
                a["res__dof_vel"][i, substeps] - b["res__dof_vel"][i, substeps]
            ).max()
        )
        for i, label in enumerate(labels)
    }
    grav = by_case.get("gravity_only", math.nan)
    damp = max((v for k, v in by_case.items() if k.startswith("damp_")), default=0.0)
    step = max((v for k, v in by_case.items() if k.startswith("step_")), default=0.0)
    lines.append("  Attribution:")
    lines.append(
        f"    gravity_only (no drive torque)      |d qd|inf = {grav:.3e}"
        "   <- articulation integration alone"
    )
    lines.append(f"    step_*       (stiffness term only)  |d qd|inf = {step:.3e}")
    lines.append(f"    damp_*       (damping term only)    |d qd|inf = {damp:.3e}")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Diff two paired drive-response probe results."
    )
    parser.add_argument(
        "--compare",
        nargs=2,
        metavar=("REFERENCE_NPZ", "TEST_NPZ"),
        required=True,
        help="Two drive-probe result files to diff (IsaacLab first by convention).",
    )
    args = parser.parse_args()
    print(compare(args.compare[0], args.compare[1]))


if __name__ == "__main__":
    main()
